apiVersion: v1
kind: Service
metadata:
  name: openwebui-service
  namespace: llm
  labels:
    app: open-webui
    app.kubernetes.io/part-of: llm-devops-project
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
